#!/usr/bin/env bash

set -e

. ~/.asdf/asdf.sh


APP_NAME=correcthorse_main
APP_VSN=`head VERSION | tr -d "\n"`
SECRET_KEY_BASE_FILE=/opt/src/deploy/secret_key_base

echo $APP_NAME
echo $APP_VSN


rm -rf /opt/build
mkdir -p /opt/build
mkdir -p /opt/src/deploy/release/
echo '*' > /opt/src/deploy/release/.gitignore
cp -r .git /opt/build
cd /opt/build
git checkout -f 


# Install updated versions of hex/rebar
mix local.rebar --force
mix local.hex --if-missing --force



## Secret key base

mix deps.get
if [ -f "$SECRET_KEY_BASE_FILE" ]; then
    export SECRET_KEY_BASE=`head "$SECRET_KEY_BASE_FILE" | tr -d '\n'`
else
    export MIX_ENV=dev
    mix compile
    export SECRET_KEY_BASE=`mix phx.gen.secret | tr -d '\n' `
    echo $SECRET_KEY_BASE > "$SECRET_KEY_BASE_FILE"
fi

export MIX_ENV=prod

mix deps.get --only prod

# do the asset stuff
npm install --prefix ./apps/correcthorse_web/assets
npm run deploy --prefix ./apps/correcthorse_web/assets

mix phx.digest


# Build the release
mix release $APP_NAME

# tar the release
cd "_build/prod/rel/$APP_NAME/"
tar zcvf /opt/src/deploy/release/$APP_NAME.tar.gz  .



exit 0
