#!/usr/bin/env bash

set -e

. ~/.asdf/asdf.sh

cd /opt/build

APP_NAME=correcthorse_main
APP_VSN=`head VERSION | tr -d "\n"`

echo $APP_NAME
echo $APP_VSN


mkdir -p /opt/build/rel/artifacts

# Install updated versions of hex/rebar
mix local.rebar --force
mix local.hex --if-missing --force

export MIX_ENV=dev
export SECRET_KEY_BASE=`mix phx.gen.secret | tr -d \'\n\' `

export MIX_ENV=prod

# Fetch deps and compile
mix deps.get --only prod
# Run an explicit clean to remove any build artifacts from the host
mix do clean, compile --force

# do the asset stuff
rm -rf ./apps/correcthorse_web/assets/node_modules
npm install --prefix ./apps/correcthorse_web/assets
npm run deploy --prefix ./apps/correcthorse_web/assets

mix phx.digest


# Build the release
mix release $APP_NAME

# tar the release
cd "_build/prod/rel/$APP_NAME/releases/$APP_VSN/"
tar zcvf /opt/build/rel/artifacts/$APP_NAME.tar.gz  .



exit 0
