#!/usr/bin/env bash

set -e

. ~/.asdf/asdf.sh

. deploy/secrets/_load-secrets

mix local.rebar --force
mix local.hex --if-missing --force
mix deps.get --only prod

npm install --prefix apps/correcthorse_web/assets
npm run deploy --prefix apps/correcthorse_web/assets

mix phx.digest

mix compile

mix release correcthorse_main

cd _build/prod/rel/correcthorse_main

tar zcvf ../correcthorse_main.tar.gz .


