#!/usr/bin/env bash

set -e

. ~/.asdf/asdf.sh


APP_NAME=correcthorse_main
APP_VSN=`head VERSION | tr -d "\n"`

echo $APP_NAME
echo $APP_VSN


rm -rf /opt/build
mkdir -p /opt/build
mkdir -p /opt/src/deploy/release/
echo '*' > /opt/src/deploy/release/.gitignore
cp -r .git /opt/build
cd /opt/build
git checkout -f 

## Secret keys 
release_vars=`cat "/opt/src/deploy/release_vars"`

for var in $release_vars
do
    file="/opt/src/deploy/secrets/$var"
    if [ -f "$file" ]; then
        export $var=`head "$file" | tr -d '\n'`
    else
        echo "***PROBLEM****"
        echo "$file not found. bin/initialise-secrets needs to be run."
        echo 
        exit 1
    fi
done


export MIX_ENV=prod
# Install updated versions of hex/rebar
mix local.rebar --force
mix local.hex --if-missing --force

mix deps.get --only prod
mix compile

# do the asset stuff
npm install --prefix ./apps/correcthorse_web/assets
npm run deploy --prefix ./apps/correcthorse_web/assets

mix phx.digest


# Build the release
mix release $APP_NAME

# tar the release
cd "_build/prod/rel/$APP_NAME/"
tar zcvf /opt/src/deploy/release/$APP_NAME.tar.gz  .



exit 0
