#!/usr/bin/env bash

set -e

. ~/.asdf/asdf.sh

. deploy/secrets/_load-secrets

mix local.rebar --force
mix local.hex --if-missing --force
mix deps.get --only prod

if [ -d "apps" ]; then
    asset_dirs=`find apps -regex '.*/assets/package.json$' | xargs -I % dirname %`
else
    asset_dirs=`find lib -regex '.*/assets/package.json$' | xargs -I % dirname %`
fi

for ad in $asset_dirs
do
    npm install --prefix $ad
    npm run deploy --prefix $ad
done

mix phx.digest

mix compile

mix release correcthorse_main

cd _build/prod/rel/correcthorse_main

tar zcvf ../correcthorse_main.tar.gz .


