version: 2  
jobs:  
  build:  
    parallelism: 1  
    docker:  
      - image: circleci/elixir:latest
        environment:  
          MIX_ENV: test

    working_directory: ~/app  

    steps:  
      - checkout  

      - run: mix local.hex --force  
      - run: mix local.rebar --force  

      - restore_cache:  
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile  
      - save_cache:  
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache: 
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - run: mix test  # run all tests in project

      - store_test_results:  
          path: _build/test/lib/correct-horse-elixir
